<!DOCTYPE html>
<html lang="en">
<head>
    <base href="<?= BASE_URL ?>">
    <link rel="stylesheet" href="./style/style.css">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <main>
    "<div class='home-buttons'>
                <button id='siniestros'>Siniestros</button>
                <button id='aseguradoras'>Aseguradoras</button>
              </div>";
    