<?php require_once './templates/layout/header.phtml' ?>

<h1>Aseguradoras</h1>
<div class='accordion'>

<?php foreach ($aseguradoras as $key => $aseguradora): 
    ?> 
        <button class='accordion-btn aseguradoraBtn' id='accordion-btn-$key'>
        <?php echo'Aseguradora: '. $aseguradora->Nombre ?>
        </button>
        <div class='accordion-content' id='accordion-content-$key'>
        <a href='aseguradora/<?php echo $aseguradora->ID_Aseguradora ?>'><?php echo 'Ver Siniestros'; ?></a>
        </div>
        <div>
            <button class='abm-btn' id='modificarBtn'>Modificar</button>
            <button class='abm-btn' id='EliminarBtn'>Eliminar</button>
        </div>

        <?php endforeach ?>  
</div>
<div class = btn-back>
<button id='back'>Atrás</button>
<button class='abm-btn'id='agregarBtn'>Agregar Aseguradora</button>

</div>



<?php require_once './templates/layout/footer.phtml' ?>