<?php require_once './templates/layout/header.phtml'?>
<?php if (!empty($error)): ?>
    <div class="" role="alert">
        <?= htmlspecialchars($error) ?>
    </div>
<?php endif; ?>
    <form action='login' method='POST' >
        <div class='form-login'>
            <label for='email' class='formLoginLabel' id='email' name='email' >Usuario</label>
            <input type='text' class='formLoginBtn' name='email' id='email' placeholder="Introduce tu usuario" required>
            <label for='password' class='formLoginLabel' id='password' name='password' >Contraseña</label>
            <input type='password' class='formLoginBtn' name='password' id='password'placeholder="Introduce tu contraseña"  required>
            <button type='submit' class='btnLogin'>login</button>
        </div>
    </form>
    
<?php require_once './templates/layout/footer.phtml'?>