<?php require_once './templates/layout/header.phtml'?>

    <form method='post' action='login'>
        <div class=''>
            <label for='email' class='' id='email' name='email' required>Usuario</label>
            <input type='text' class='' id='email'>
            <label for='password' class='' id='password' name='password' required>Contraseña
            <input type='password' class='' id='email'>
        </div>
        <button type='submit' class=''>login</button>
    </form>
<?php require_once './templates/layout/footer.phtml'?>