<?php require_once './templates/layout/header.phtml' ?>

 <form action='siniestroAdd' method='POST'>
    <h1>Agregar Siniestro</h1>
    <label>Aseguradora</label>
                <select  name="aseguradora" class="">
                    <?php foreach ($aseguradoras as $aseguradora): ?>
                        <option value=<?php echo $aseguradora->ID_Aseguradora ?>><?php echo $aseguradora->Nombre ?></option>
                    <?php endforeach ?>
                </select>
    <div>
        <label for='asegurado' class='labelAdd'>Nombre Asegurado</label>
        <input type='text' name='asegurado' class='inputAdd' required>
        <label for='typeSiniestro' class='labelAdd'>Tipo de Siniestro</label>
        <input type='text' name='typeSiniestro' class='inputAdd' required>
        <label for='date' class='labelAdd'>Fecha</label>
        <input type='text' name='date' class='inputAdd' required>
    </div>
    <button type='submit'>Guadar</button>
</form>

<?php require_once './templates/layout/footer.phtml' ?>