<?php require 'templates/layout/header.phtml' ?>

<h1>Siniestros</h1>
        <div class='accordion'>
        <?foreach ($siniestros as $key => $siniestro):?>
                <button class='accordion-btn' id='accordion-btn-$key'>
                    Nombre y Apellido: <?$siniestro->Asegurado?> - Fecha: <?$siniestro->Fecha?>
                </button>
                <div class='accordion-content' id='accordion-content-$key'>
                    <p>ID del Siniestro: <?$siniestro->ID_Siniestro?></p>
                    <p>Descripción: <?$siniestro->Tipo_Siniestro?></p>
                    <p>ID de la Aseguradora: <?$siniestro->ID_Aseguradora?></p>

                </div>
                <?php endforeach ?>
        </div>
        </main>
              <div class='btn-back'>
                  <button id='back'>Atrás</button>
              </div>

<?php require 'templates/layout/footer.phtml' ?>

