
<head>
    <base href="<?= BASE_URL ?>">
    <link rel="stylesheet" href="./style/style.css">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Peritajes App</title>
</head>
<body>
    <nav>
        <button id="btnToggle" class="menuToggle" >
            <img src="images/menutoggle.png" alt="Menu Hamburguesa">
        </button>
        <ul class="menu" id="menu">
            <li><a href="home">INICIO</a></li>
            <li><a href="aseguradoras">ASEGURADORAS</a></li>
            <li><a href="siniestros">SINIESTROS</a></li>
            <li><a href="showlogin">LOGIN</a></li>
        </ul>
    </nav>
</body>














